# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookshot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bookshot.Book'),
            preserve_default=False,
        ),
    ]
