# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 14:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshot', '0002_quote_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='book',
        ),
    ]
