# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 18:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookshot', '0003_remove_quote_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='readers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quote',
            name='book',
            field=models.ForeignKey(null=True, blank=True, default = None, on_delete=django.db.models.deletion.CASCADE, to='bookshot.Book'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quote',
            name='photo',
            field=models.ImageField(upload_to='bookshot'),
        ),
    ]
