# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 18:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshot', '0006_auto_20160701_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='book',
        ),
    ]
