# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 18:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookshot', '0007_remove_quote_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='book',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookshot.Book'),
        ),
    ]
