# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshot', '0008_quote_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='date',
        ),
        migrations.AddField(
            model_name='quote',
            name='created_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='updated_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
