# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bookshot', '0009_auto_20160703_0654'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='_raw_response',
            field=jsonfield.fields.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn13',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
