# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshot', '0010_auto_20160710_0436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='isbn13',
        ),
        migrations.AddField(
            model_name='book',
            name='_isbn13',
            field=models.CharField(blank=True, db_column='isbn13', max_length=13),
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='_raw_response',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_url',
            field=models.URLField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
