# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshot', '0011_auto_20160714_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_url',
            field=models.URLField(blank=True, default='{}', max_length=300, null=True),
        ),
    ]
